./node_modules/babel-cli/bin/babel-node.js opensooq-downloader.js --count 100 --cat عقارات/شقق && 
./node_modules/babel-cli/bin/babel-node.js opensooq-downloader.js --count 100 --cat عقارات/فلل-قصور && 
./node_modules/babel-cli/bin/babel-node.js opensooq-downloader.js --count 100 --cat عقارات/غرف-للسكن && 
./node_modules/babel-cli/bin/babel-node.js opensooq-downloader.js --count 100 --cat عقارات/أبنية-تجارية && 
./node_modules/babel-cli/bin/babel-node.js opensooq-downloader.js --count 100 --cat عقارات/عمارات && 
./node_modules/babel-cli/bin/babel-node.js opensooq-downloader.js --count 100 --cat عقارات/أراضي-مزارع && 
./node_modules/babel-cli/bin/babel-node.js opensooq-downloader.js --count 100 --cat عقارات/شاليهات-مصايف-استراحات && 
./node_modules/babel-cli/bin/babel-node.js opensooq-downloader.js --count 100 --cat عقارات/عقارات-اخرى' && 
./node_modules/babel-cli/bin/babel-node.js opensooq-downloader.js --count 100 --cat سيارات-ومركبات/سيارات-للبيع && 
./node_modules/babel-cli/bin/babel-node.js opensooq-downloader.js --count 100 --cat سيارات-ومركبات/سيارات-للإيجار && 
./node_modules/babel-cli/bin/babel-node.js opensooq-downloader.js --count 100 --cat سيارات-ومركبات/دراجات-نارية  && 
./node_modules/babel-cli/bin/babel-node.js opensooq-downloader.js --count 100 --cat موبايل-تابلت/موبايل && 
./node_modules/babel-cli/bin/babel-node.js opensooq-downloader.js --count 100 --cat موبايل-تابلت/تابلت && 
./node_modules/babel-cli/bin/babel-node.js opensooq-downloader.js --count 100 --cat موبايل-تابلت/اكسسوارات-موبايل-تابلت && 
./node_modules/babel-cli/bin/babel-node.js opensooq-downloader.js --count 100 --cat اجهزة-الكترونيات/لابتوب-كمبيوتر && 
./node_modules/babel-cli/bin/babel-node.js opensooq-downloader.js --count 100 --cat اجهزة-الكترونيات/تلفزيون-شاشات && 
./node_modules/babel-cli/bin/babel-node.js opensooq-downloader.js --count 100 --cat اجهزة-الكترونيات/كاميرات-تصوير && 
./node_modules/babel-cli/bin/babel-node.js opensooq-downloader.js --count 100 --cat اجهزة-الكترونيات/غسالات-ملابس-نشافات && 
./node_modules/babel-cli/bin/babel-node.js opensooq-downloader.js --count 100 --cat أثاث-ديكور/أثاث && 
./node_modules/babel-cli/bin/babel-node.js opensooq-downloader.js --count 100 --cat أثاث-ديكور/ديكور-المنزل-تأثيث && 
./node_modules/babel-cli/bin/babel-node.js opensooq-downloader.js --count 100 --cat أثاث-ديكور/ادوات-المطبخ-ضيافة && 
./node_modules/babel-cli/bin/babel-node.js opensooq-downloader.js --count 100 --cat أثاث-ديكور/أدوات-منزلية && 
./node_modules/babel-cli/bin/babel-node.js opensooq-downloader.js --count 100 --cat أثاث-ديكور/أثاث-ديكور-اخرى && 
./node_modules/babel-cli/bin/babel-node.js opensooq-downloader.js --count 100 --cat لوازم-الأطفال-و-الألعاب/اثاث-وغرف-نوم-اطفال && 
./node_modules/babel-cli/bin/babel-node.js opensooq-downloader.js --count 100 --cat لوازم-الأطفال-و-الألعاب/عربات-ومقاعد-أطفال
